name: 'Create ClickUp tasks from commits'
description: 'Automatically create ClickUp tasks from commits'
author: 'Bennett Benedict'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

inputs:
  CLICKUP_TOKEN:
    description: 'ClickUp TOken'
    required: true
  LIST_ID:
    description: 'ClickUp List where the task is to be created'
    required: true
  MESSAGE:
    description: 'Commit message'
    required: true
  ASSIGNEES:
    description: 'Task assignees'
    required: true
  STATUS:
    description: 'Task status'
    required: true

runs:
  using: node20
  main: dist/index.js
