name: RUN

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: npm install && npm run bundle

      - uses: ./
        with:
          CLICKUP_TOKEN: ${{secrets.TOKEN}}
          LIST_ID: ${{secrets.LIST_ID}}
          TASK_STATUS: ${{secrets.STATUS}}
          ASSIGNEES: ${{secrets.ASSIGNEES}}
          FIELDS: ${{secrets.FIELDS}}
          MESSAGE: ${{github.event.head_commit.message}}
          AUTHOR:
            ${{ github.event.commits[0].author.username ||
            github.event.commits[0].author.login }}
